FIT5120 - VicEnerG/Controllers/CalculatorController.cs
using FIT5120___VicEnerG.Models;
using FIT5120___VicEnerG.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FIT5120___VicEnerG.Controllers
{
    public class CalculatorController : Controller
    {
        private VicEnerG_ModelContainer db = new VicEnerG_ModelContainer();
        // GET: Calculator

        [HttpGet]
        public ActionResult CalculateOutput()
        {
            var Model = new CalculatorViewModel();
            return View(Model);
        }
        //This function is for the logic of when user input another postcode in the input box and there will be a
        // bar chart with two columns generate.
        public async Task<String> Compare(int Postcode, int NumberPanels)
        {
            //Initialize
            VicEnerGSystem VEG = new VicEnerGSystem();
            //Use the postcode which from the input box and check the data in staion
            List<double> Coordinates = await VEG.GetGeocode(Postcode);
            IList<Station> StationList = db.StationSet.ToList();
            int NearestStationID = VEG.FindNearestStation(Coordinates, StationList);
            Station TargetStation = db.StationSet.Find(NearestStationID);
            Calculator calculator = new Calculator();
            IList<double> MonthlyOutput = calculator.CalculateSolarOutput(TargetStation.StationMonthlyRadiations(), NumberPanels);

            var dataList = new
            {
                Postcode = Postcode,
                OutputList = MonthlyOutput
            };
            ViewBag.stationList = dataList;
            var jsonData = JsonConvert.SerializeObject(dataList);
            return jsonData;
        }

        // This is the controller for Calculator page. It collectes data from the website, pass the data through different methods
        // Eventually display the information on the webpage with a Viewmodel.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CalculateOutput([Bind(Include = "Postcode, NumberPanels")] CalculatorViewModel Model)
        {
            // Validate the input are valid
            if (ModelState.IsValid)
            {
                // Initial the VicEnerG System
                VicEnerGSystem VEG = new VicEnerGSystem();
                // Pass the postcode to GetGeocode method and return a list that contained the latitude and longitude of the postcode
                List<double> Coordinates = await VEG.GetGeocode(Model.Postcode);
                // Get all information from all the staion in Victoria from the database
                IList<Station> StationList = db.StationSet.ToList();
                // Pass the coordinate of the postcode to FindNearestStation method along with all station data
                int NearestStationID = VEG.FindNearestStation(Coordinates, StationList);
                // Find the corresponding station based on the given station number 
                Station TargetStation = db.StationSet.Find(NearestStationID);
                // Initial the calculator
                Calculator calculator = new Calculator();
                // Calculate the 12 months solar output of a given station with specific amount of panels installed
                IList<double> MonthlyOutput = calculator.CalculateSolarOutput(TargetStation.StationMonthlyRadiations(), Model.NumberPanels);
                // Calculate the amount of CO2 corresponding to the amount of kwh electricity
                double CO2 = calculator.CalculateCO2(MonthlyOutput.Sum());
                // Get all information of all appliances from the database
                IList<Appliance> ApplianceList = db.ApplianceSet.ToList();
                // Pass the parameter to the calculator to calculate extra hours for each appliances
                IDictionary<String, List<int>> ApplianceExtraHours = calculator.CalculateUsage(ApplianceList, MonthlyOutput);

                // Calculate the monthly average energy output of Victoria by given solar radiation
                IList<double> VictoriaRadiation = new List<double>()
                {187.84, 154.0059259, 120.1309259, 94.06222222, 68.84055556, 45.70203704, 60.65203704, 82.14037037, 110.3937037, 129.3333333, 179.1027778, 191.8737037};
                IList<double> VictoriaAverage = calculator.CalculateSolarOutput(VictoriaRadiation, Model.NumberPanels);

                // Pass all necessary information to the viewModel and Viewbag
                Model.OutputList = MonthlyOutput;
                Model.AnnualOutput = MonthlyOutput.Sum();
                Model.Station = TargetStation;
                Model.CO2 = CO2;
                Model.Extrahours = ApplianceExtraHours;
                Model.VictoriaAverage = VictoriaAverage;
                ViewBag.Month = Enum.GetNames(typeof(Months)).ToList();
            }
            return View(Model);
        }
    }

    // Create a enum to store months name
    public enum Months{
        Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
    }
}

FIT5120 - VicEnerG/Controllers/CarbonController.cs
using FIT5120___VicEnerG.Models;
using FIT5120___VicEnerG.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FIT5120___VicEnerG.Controllers
{
    public class CarbonController : Controller
    {
        private VicEnerG_ModelContainer db = new VicEnerG_ModelContainer();

        // GET: Carbon
        [HttpGet]
        public ActionResult CalculateCarbon()
        {
            var Model = new CarbonViewModel();
            // Annual Solar output of Melbourne CBD (postcode 3000)
            PostcodeData Melbourne = db.PostcodeDatas.Find(3000);
            ViewBag.Message = Melbourne.solarOutput;
            return View(Model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CalculateCarbon([Bind(Include = "Postcode, NumberPanels")] CarbonViewModel Model)
        {
            if (ModelState.IsValid)
            {
                // Initial the VicEnerG System
                VicEnerGSystem VEG = new VicEnerGSystem();
                // Pass the postcode to GetGeocode method and return a list that contained the latitude and longitude of the postcode
                List<double> Coordinates = await VEG.GetGeocode(Model.Postcode);
                // Get all information from all the staion in Victoria from the database
                IList<Station> StationList = db.StationSet.ToList();
                // Pass the coordinate of the postcode to FindNearestStation method along with all station data
                int NearestStationID = VEG.FindNearestStation(Coordinates, StationList);
                // Find the corresponding station based on the given station number 
                Station TargetStation = db.StationSet.Find(NearestStationID);
                // Initial the calculator
                Calculator calculator = new Calculator();
                // Calculate the 12 months solar output of a given station with specific amount of panels installed
                IList<double> MonthlyOutput = calculator.CalculateSolarOutput(TargetStation.StationMonthlyRadiations(), Model.NumberPanels);
                // Calculate the amount of CO2 corresponding to the amount of kwh electricity
                double CO2 = calculator.CalculateCO2(MonthlyOutput.Sum());
                // Calculate the hours for trees in Victoria CBD to absorb given CO2
                int AbsorbHours = calculator.CalculateAbsorptionHours(CO2);
                // This method will calculate the equivalent kilometers that a passenger vehicle and light suv of given CO2
                int LightVehicle = calculator.CalcualteKMForLightCar(CO2);
                // This method will calculate the equivalent kilometers that the heavy suv of given CO2
                int HeavyVehicle = calculator.CalcualteKMForHeaveyCar(CO2);
                // This method will calculate how many times that a phone can be fully charged by given CO2
                int PhoneCharges = calculator.CalculatePhoneCharged(CO2);
                // This method will calculate the equivalent gallons of gasoline consumed by giving CO2
                int Gallons = calculator.CalculateGasoline(CO2);
                // Find the annual solar output data of given postcode
                PostcodeData PostcodeOutput = db.PostcodeDatas.Find(Model.Postcode);
                double PostcodeCO2 = 0;
                if (PostcodeOutput != null)
                {
                    PostcodeCO2 = calculator.CalculateCO2(PostcodeOutput.solarOutput);
                }
                // Get all annual post code data from the database
                IList<PostcodeData> PostcodeDataList = db.PostcodeDatas.ToList();
                // This method will calculate the annual solar output generated by solar panels in Victoria
                double VictoriaOutput = calculator.CalculateVictoriaOutput(PostcodeDataList);
                // Calculate the CO2 of annual Postcode data and annual Victoria data
                double VictoriaCO2 = calculator.CalculateCO2(VictoriaOutput);
                // Pass all necessary information to the viewModel and Viewbag
                Model.CO2 = CO2;
                Model.AbsorbHours = AbsorbHours;
                Model.LightVehicle = LightVehicle;
                Model.HeavyVehicle = HeavyVehicle;
                Model.PhoneCharges = PhoneCharges;
                Model.Gasoline = Gallons;
                Model.SuburbTotalCO2 = PostcodeCO2;
                Model.StateMonthlyCO2 = Math.Round(VictoriaCO2 / 12,2);
            }
            return View(Model);
        }

    }
}

FIT5120 - VicEnerG/Controllers/WaterController.cs
using FIT5120___VicEnerG.Models;
using FIT5120___VicEnerG.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FIT5120___VicEnerG.Controllers
{
    public class WaterController : Controller
    {
        private VicEnerG_ModelContainer db = new VicEnerG_ModelContainer();
        // GET: Water
        [HttpGet]
        public ActionResult CalculateWater()
        {
            var Model = new WaterViewModel();
            return View(Model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CalculateWater([Bind(Include = "Postcode, RoofSize")] WaterViewModel Model)
        {
            if (ModelState.IsValid)
            {// Initial the VicEnerG System
                VicEnerGSystem VEG = new VicEnerGSystem();
                // Pass the postcode to GetGeocode method and return a list that contained the latitude and longitude of the postcode
                List<double> Coordinates = await VEG.GetGeocode(Model.Postcode);
                // Get all information from all the staion in Victoria from the database
                IList<Station> StationList = db.StationSet.ToList();
                // Pass the coordinate of the postcode to FindNearestStation method along with all station data
                int NearestStationID = VEG.FindNearestStation(Coordinates, StationList);
                // Find the corresponding station based on the given station number 
                Station TargetStation = db.StationSet.Find(NearestStationID);
                // Initial the calculator
                Calculator calculator = new Calculator();
                // Calculate the annual rainfall of the postcode
                int AnnualRainFall = (int)TargetStation.StationMonthlyRainfalls().Sum();
                // Calculate the amount of the rainwater harvest by given roofSize
                IList<double> MonthlyHarvest = calculator.CalculateRainHarvested(TargetStation.StationMonthlyRainfalls(), Model.RoofSize);
                double TotalRainHarvest = MonthlyHarvest.Sum();

                // Calculate the monthly average rainwater harvested of Victoria by given size of Roof
                IList<double> VictoriaAverageRainFall = new List<double>()
                {84.984,28.56133333,55.52066667,26.84333333,67.44466667,89.38933333,44.346,78.926,55.524,89.218,39.59466667,45.30933333};
                IList<double> VictoriaAverageHarvest = calculator.CalculateRainHarvested(VictoriaAverageRainFall, Model.RoofSize);


                // Pass all necessary information to the viewModel and Viewbag
                Model.AnnualRainFall = AnnualRainFall;
                Model.MonthlyHarvest = MonthlyHarvest;
                Model.RainHarvest = TotalRainHarvest;
                Model.VictoriaAverage = VictoriaAverageHarvest;
                ViewBag.Month = Enum.GetNames(typeof(Months)).ToList();
            }
            return View(Model);
        }
    }
}

FIT5120 - VicEnerG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - VicEnerG</title>
    <link rel="shortcut icon" type="image/ico" href="~/images/logo/Icon.png">
    @Scripts.Render("~/Pages_Resource/js/pagejs")
    @Scripts.Render("~/bundles/chartjs")
    @Styles.Render("~/Pages_Resource/css/pagecss")
    <!-- google fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'><!--web font-->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">
    <!-- //google fonts -->
</head>
@{
    if (ViewBag.Title == "Home")
    {
        ViewBag.BodyClass = "home-body";
    }
    else {
        ViewBag.BodyClass = "page-body";
    }

}
    <body class=@ViewBag.BodyClass>
        <style>
            .active1 a {
                text-decoration: underline;
                font-weight: bold;
            }
            .active3 .dropbtn {
                text-decoration: underline;
                font-weight: bold;
            }
            .active2 a {
                text-decoration: underline;
                font-weight: bold;
            }
        </style>
        <div class="w3l-banner">
            <div class="wthree-dot">
                <!-- nav -->
                <div class="header w3layouts">
                    <div class="container-fluid">
                        <nav class="navbar navbar-default navbar-fixed-top">
                            <div class="navbar-header navbar-left">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a href="~/Home/Index"><img id="project-logo" src="~/images/logo/Logo.png" width="100" height="80" /></a>
</div>
                            <!-- Collect the nav links, forms, and other content for toggling -->
                            <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
                                <nav id="navigation"> 
                                    <ul class="nav navbar-nav">
                                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active1" : "")">
                                            @*<a href="~/Home/Index">Home</a>*@
                                            @Html.ActionLink("Home", "Index", "Home")
                                        </li>

                                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "CalculateOutput" ? "active1" : "")">
                                            @Html.ActionLink("SOLAR CALCULATOR", "CalculateOutput", "Calculator")
                                            @*<a href="~/Calculator/CalculateOutput">SOLAR CALCULATOR</a>*@
                                        </li>
                                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "CalculateCarbon" ? "active1" : "")">
                                            @Html.ActionLink("CARBON CALCULATOR", "CalculateCarbon", "Carbon")
                                            @*<a href="~/Carbon/CalculateCarbon">CARBON CALCULATOR</a>*@
                                        </li>
                                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "CalculateWater" ? "active1" : "")">
                                            @Html.ActionLink("WATER CALCULATOR", "CalculateWater", "Water")
                                            @*<a href="~/Water/CalculateWater">WATER CALCULATOR</a>*@
                                        </li>
                                        <li class="dropdown @(ViewContext.RouteData.Values["Action"].ToString() == "SolarInfo"||ViewContext.RouteData.Values["Action"].ToString()=="SolarRebates"||ViewContext.RouteData.Values["Action"].ToString()=="CarbonInfo" ? "active3" : "")">
                                            <a class="dropbtn" style="margin-top: 1px;">
                                                INFORMATION
                                                <i class="fa fa-caret-down"></i>
                                            </a>
                                            <ul>
                                                <li class="dropdown-content ">
                                                    @Html.ActionLink("SOLAR PANELS", "SolarInfo", "Home")
                                                    @Html.ActionLink("SOLAR REBATES", "SolarRebates", "Home")
                                                    @Html.ActionLink("CARBON FOOTPRINT", "CarbonInfo", "Home")
                                                    @*<a href="~/Home/SolarInfo">SOLAR PANELS</a>
                                                    <a href="~/Home/SolarRebates">SOLAR REBATES</a>
                                                    <a href="~/Home/CarbonInfo">CARBON FOOTPRINT</a>*@
                                                </li>
                                            </ul>
                                        </li>

                                        <!--

                        <li class="dropdown">
                            <a class="dropbtn" style="margin-top: 1px;">
                                CALCULATOR
                                <i class="fa fa-caret-down"></i>
                            </a>
                            <ul>
                                <li class="dropdown-content">
                                    @Html.ActionLink("SOLAR OUTPUT", "CalculateOutput", "Calculator")
                                    @Html.ActionLink("CARBON FOOTPRINT", "CalculateCarbon", "Carbon")
                                    @Html.ActionLink("WATER RECYCLING", "CalculateWater", "Water")
                                    @*<a href="~/Calculator/CalculateOutput">SOLAR OUTPUT</a>
    <a href="~/Carbon/CalculateCarbon">CARBON FOOTPRINT</a>*@
                                </li>
                            </ul>
                        </li>
                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "CarbonInfo" ? "active1" : "")">
                            @Html.ActionLink("Carbon Information", "CarbonInfo", "Home")
                            @*<a href="~/Home/CarbonInfo">Carbon Information</a>*@
                        </li>
                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "SolarInfo" ? "active1" : "")">
                            @Html.ActionLink("Solar Information", "SolarInfo", "Home")
                            @*<a class="navA" href="~/Home/SolarInfo">Solar Information</a>*@
                        </li>
                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "SolarRebates" ? "active1" : "")">
                            @Html.ActionLink("Solar Rebates", "SolarRebates", "Home")
                            @*<a href="~/Home/SolarRebates">Solar Rebates</a>*@
                        </li>
                            -->
                                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "AboutUs" ? "active1" : "")">
                                            @Html.ActionLink("About Us", "AboutUs", "Home")
                                            @*<a href="~/Home/AboutUs">About Us</a>*@
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </nav>
                    </div>
                </div>
                <!-- //nav -->
            </div>
        </div>



            <div id="page-container">
                <div id="content-wrap">
                    @RenderBody()
                    <div class="push"></div>
                    <footer id="footer">
                        <div class="wthree_copy_right" id="wthree_copy_right">
                            <div class="container">
                                <p>Copyright &copy; @DateTime.Now.Year. Team VicEnerG Australia  &ensp;&ensp;&ensp;&ensp;&ensp;&ensp; <a href="~/Home/Disclaimer">Disclaimer</a></p>
                            </div>
                        </div>
                    </footer>
                </div>
            </div>
            <!-- smooth scrolling-bottom-to-top -->
            <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>

            @RenderSection("scripts", required: false)
        </body>
        
</html>